-- db/seed.sql — deterministic example data for the amber schema.
-- Re-runnable: truncates and rebuilds everything EXCEPT amber.books.
-- Values are generated by modular arithmetic (not random()), so every run
-- produces byte-identical rows. Each student has a latent "ability" derived
-- from their id, so struggle rate, comprehension and pace correlate.

BEGIN;

SELECT setseed(0.42);  -- guard, in case random() is added later

TRUNCATE amber.comprehension_answers, amber.comprehension_questions,
         amber.reading_events, amber.reading_sessions,
         amber.student_word_status, amber.students, amber.classrooms, amber.teachers
  RESTART IDENTITY CASCADE;

-- ── teachers ────────────────────────────────────────────────────────────────
INSERT INTO amber.teachers (id, email, name) VALUES
  (1, 'r.alvarez@amber.test',   'Rosa Alvarez'),
  (2, 'd.okafor@amber.test',    'Daniel Okafor'),
  (3, 's.lindqvist@amber.test', 'Sara Lindqvist');
SELECT setval('amber.teachers_id_seq', 3);

-- ── classrooms: 6, two per teacher ──────────────────────────────────────────
INSERT INTO amber.classrooms (id, teacher_id, name)
SELECT i, ((i - 1) % 3) + 1,
       (ARRAY['English 8A','English 8B','Reading Lab',
              'Literature 9','Humanities 8','Book Club'])[i]
FROM generate_series(1, 6) AS i;
SELECT setval('amber.classrooms_id_seq', 6);

-- ── students: 30, five per classroom ────────────────────────────────────────
INSERT INTO amber.students (id, classroom_id, name, email, typical_reading_hour)
SELECT i,
       ((i - 1) % 6) + 1,
       n.name,
       -- slugify: strip periods from honorifics first, then spaces -> dots,
       -- so "Mr. Potato Head" becomes mr.potato.head@ (not mr..potato.head@)
       lower(regexp_replace(regexp_replace(trim(n.name), '\.', '', 'g'),
                            '\s+', '.', 'g')) || '@amber.test',
       16 + ((i * 7) % 5)
FROM generate_series(1, 30) AS i
CROSS JOIN LATERAL (SELECT
    (ARRAY['Woody','Buzz Lightyear','Jessie','Rex','Hamm',
           'Slinky Dog','Bo Peep','Mr. Potato Head','Mrs. Potato Head','Sarge',
           'Wheezy','Lenny','Trixie','Buttercup','Dolly',
           'Mr. Pricklepants','Chuckles','Barbie','Ken','Lotso',
           'Big Baby','Stretch','Twitch','Sparks','Forky',
           'Ducky','Bunny','Duke Caboom','Gabby Gabby','Giggle McDimples'])[i]
) AS n(name);
SELECT setval('amber.students_id_seq', 30);

-- ── reading_sessions: 3 per student = 90 ────────────────────────────────────
INSERT INTO amber.reading_sessions
  (student_id, book_id, started_at, ended_at, start_page, end_page, end_reason)
SELECT st.id, bk.id,
       v.base_ts,
       v.base_ts + make_interval(mins => v.mins),
       v.start_page,
       LEAST(v.start_page + v.pages_read, bk.total_pages),
       CASE WHEN g.n = 3 THEN 'timeout' ELSE 'finished' END
FROM amber.students st
JOIN amber.books bk ON bk.id = ((st.id - 1) % 6) + 1
CROSS JOIN generate_series(1, 3) AS g(n)
CROSS JOIN LATERAL (SELECT
    (CURRENT_TIMESTAMP - make_interval(days => 75 - g.n * 20 + (st.id % 9)))::timestamp,
    (12 + ((st.id * g.n) % 34)),
    (1 + (g.n - 1) * (bk.total_pages / 6)),
    (8 + ((st.id + g.n) % 22))
) AS v(base_ts, mins, start_page, pages_read);

-- ── reading_events: exactly 10 per student = 300 ────────────────────────────
INSERT INTO amber.reading_events
  (student_id, book_id, event_type, word, page, line_number, occurred_at)
SELECT st.id, bk.id,
       ev.event_type,
       CASE WHEN ev.event_type = 'clean' THEN NULL ELSE w.word END,
       1 + ((st.id * g.n * 13) % bk.total_pages),
       1 + ((st.id + g.n) % 28),
       CURRENT_TIMESTAMP - make_interval(days => (g.n * 7 + st.id) % 90,
                                         mins => (st.id * g.n) % 600)
FROM amber.students st
JOIN amber.books bk ON bk.id = ((st.id - 1) % 6) + 1
CROSS JOIN generate_series(1, 10) AS g(n)
-- Struggle share is ability-weighted: a weak reader (ability 0) struggles on
-- ~45% of events, a strong one (ability 1) on ~20%. Yields ~90 struggle rows.
CROSS JOIN LATERAL (SELECT
    CASE
      WHEN ((st.id * g.n * 29) % 100) < (20 + 40 * (((st.id * 37) % 101) / 100.0)) THEN 'clean'
      WHEN ((st.id * g.n * 29) % 100) < (55 + 25 * (((st.id * 37) % 101) / 100.0)) THEN 'reread'
      ELSE 'struggle'
    END
) AS ev(event_type)
-- Each student draws from a narrow personal pool of 5 words, so words RECUR
-- within a student across their 10 events. Without this every (student, word)
-- pair is unique and times_struggled is always 1.
CROSS JOIN LATERAL (SELECT
    (ARRAY['inevitable','conscience','melancholy','peculiar','reluctant',
           'tremendous','deliberate','sympathy','indignant','circumstance',
           'monotonous','perpetual','acquaintance','bewildered','extravagant',
           'resolute','audacious','languid','vehement','solitude'])
      [1 + (((st.id * 3) + ((g.n - 1) % 5) * 4) % 20)]
) AS w(word);

-- ── student_word_status: AGGREGATED from struggle events, not invented ──────
INSERT INTO amber.student_word_status
  (student_id, word, status, first_struggled_at, last_struggled_at,
   times_struggled, clean_reads_since, conquered_at)
-- Lifecycle is derived, not assigned: a word is 'conquered' once the student
-- logs clean reads of it after their last struggle, 'struggling' while the
-- struggle count is still high, 'improving' in between.
WITH struggles AS (
  SELECT student_id, word, count(*)::int AS times,
         min(occurred_at) AS first_at, max(occurred_at) AS last_at
  FROM amber.reading_events
  WHERE event_type = 'struggle' AND word IS NOT NULL
  GROUP BY student_id, word
), cleans AS (
  SELECT s.student_id, s.word,
         count(e.id)::int AS clean_since,
         min(e.occurred_at) AS first_clean_at
  FROM struggles s
  LEFT JOIN amber.reading_events e
         ON e.student_id = s.student_id
        AND e.event_type = 'clean'
        AND e.occurred_at > s.last_at
  GROUP BY s.student_id, s.word
)
SELECT s.student_id, s.word,
       CASE WHEN s.times >= 2 AND c.clean_since < 2 THEN 'struggling'
            WHEN c.clean_since >= 2                 THEN 'conquered'
            ELSE 'improving' END,
       s.first_at, s.last_at, s.times, c.clean_since,
       CASE WHEN c.clean_since >= 2 THEN c.first_clean_at END
FROM struggles s JOIN cleans c USING (student_id, word);

-- ── comprehension_questions: 4 per book = 24 ────────────────────────────────
INSERT INTO amber.comprehension_questions (book_id, after_page, question, correct_answer)
SELECT bk.id,
       GREATEST(1, (bk.total_pages * g.n / 5)::int),
       'After page ' || GREATEST(1, (bk.total_pages * g.n / 5)::int)
         || ' of "' || bk.title || '", what changes for the protagonist?',
       (ARRAY['Character growth','A key conflict emerges',
              'The setting shifts','A central theme is revealed'])[g.n]
FROM amber.books bk
CROSS JOIN generate_series(1, 4) AS g(n);

-- ── comprehension_answers: 30 students x 4 questions = 120 ──────────────────
INSERT INTO amber.comprehension_answers (student_id, question_id, is_correct, answered_at)
SELECT st.id, q.id,
       ((st.id * q.id * 31) % 100) < (40 + 50 * (((st.id * 37) % 101) / 100.0)),
       CURRENT_TIMESTAMP - make_interval(days => (st.id + q.id) % 60)
FROM amber.students st
JOIN amber.comprehension_questions q ON q.book_id = ((st.id - 1) % 6) + 1;

-- ── roll raw events up into the denormalized student stat columns ───────────
WITH sess AS (
  SELECT student_id, max(end_page) AS max_page,
         avg(EXTRACT(EPOCH FROM (ended_at - started_at)) / 60.0) AS avg_mins,
         count(*) AS n_sessions
  FROM amber.reading_sessions GROUP BY student_id
), ev AS (
  SELECT student_id,
         count(*) FILTER (WHERE event_type = 'struggle')::numeric / count(*) AS struggle_rate,
         count(*) FILTER (WHERE event_type = 'reread')::numeric   / count(*) AS reread_rate
  FROM amber.reading_events GROUP BY student_id
), ans AS (
  SELECT student_id, avg(CASE WHEN is_correct THEN 1 ELSE 0 END)::numeric AS score
  FROM amber.comprehension_answers GROUP BY student_id
)
UPDATE amber.students s SET
  current_page        = sess.max_page,
  progress_percent    = round(100.0 * sess.max_page / b.total_pages, 1),
  struggle_rate       = round(ev.struggle_rate, 3),
  reread_rate         = round(ev.reread_rate, 3),
  comprehension_score = round(ans.score, 3),
  avg_session_minutes = round(sess.avg_mins::numeric, 1),
  sessions_per_week   = round(sess.n_sessions / 12.0, 2),
  current_streak_days = 1 + (s.id % 9),
  stamina_score       = round(LEAST(1.0, sess.avg_mins / 45.0)::numeric, 3),
  learning_velocity   = round(GREATEST(0, 1 - ev.struggle_rate) * ans.score, 3),
  overall_rating      = CASE
                          WHEN ans.score >= 0.75 AND ev.struggle_rate < 0.20 THEN 'thriving'
                          WHEN ans.score >= 0.50 THEN 'steady'
                          ELSE 'needs support'
                        END,
  stats_updated_at    = CURRENT_TIMESTAMP
FROM sess, ev, ans, amber.books b
WHERE sess.student_id = s.id AND ev.student_id = s.id AND ans.student_id = s.id
  AND b.id = ((s.id - 1) % 6) + 1;

COMMIT;
